# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ePI9LM05engmF8DbXFdtb-FU56HiTWV2
"""

import gensim

from gensim.models import Word2Vec,KeyedVectors

!pip install wget

!wget -c "https://s3.amazonaws.com/dl4j-distribution/GoogleNews-vectors-negative300.bin.gz"

import numpy as np

from sklearn.manifold import TSNE

import matplotlib.pyplot as plt

import gensim.downloader as api

glove_model = api.load('glove-wiki-gigaword-300')

glove_model['beautiful']

glove_model.most_similar('girl')

glove_model.most_similar(positive = ['boy' , 'queen'] , negative = ['girl'] , topn = 1)

